export const KENYAN_INSURERS = [
  'AAR Insurance Kenya',
  'APA Insurance',
  'Britam Insurance',
  'CIC Insurance',
  'First Assurance',
  'GA Insurance',
  'Heritage Insurance',
  'ICEA LION Group',
  'Jubilee Health Insurance',
  'Kenindia Assurance',
  'Kenya Orient Insurance',
  'Madison Insurance',
  'Mayfair Insurance',
  'Old Mutual General Insurance Kenya',
  'Pioneer Insurance',
  'Resolution Insurance',
  'Sanlam General Insurance',
  'TAUSI Assurance',
  'Trident Insurance',
  'UAP Old Mutual',
] as const;
